version: "3.7"
services:
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=letmein
    volumes:
      - "./data/couchdb/config:/opt/couchdb/etc/local.d/"
      - "./data/couchdb/data:/opt/couchdb/data/"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5984"]
        interval: 30s
        timeout: 10s
        retries: 5

  app:
    build: .
    command: ./wait-for-it.sh couchdb:5984 -- bash ./entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - ".:/src"
    environment:
      - COUCHDB_HOST=couchdb
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=letmein
      - env=development
    depends_on:
      - couchdb
    links:
      - couchdb